USE [master]
GO
/****** Object:  Database [DB_SMP]    Script Date: 12/26/2022 10:56:45 AM ******/
CREATE DATABASE [DB_SMP]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DB_SMP', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DB_SMP.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DB_SMP_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DB_SMP_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [DB_SMP] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DB_SMP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DB_SMP] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DB_SMP] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DB_SMP] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DB_SMP] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DB_SMP] SET ARITHABORT OFF 
GO
ALTER DATABASE [DB_SMP] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DB_SMP] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DB_SMP] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DB_SMP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DB_SMP] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DB_SMP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DB_SMP] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DB_SMP] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DB_SMP] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DB_SMP] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DB_SMP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DB_SMP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DB_SMP] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DB_SMP] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DB_SMP] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DB_SMP] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DB_SMP] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DB_SMP] SET RECOVERY FULL 
GO
ALTER DATABASE [DB_SMP] SET  MULTI_USER 
GO
ALTER DATABASE [DB_SMP] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DB_SMP] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DB_SMP] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DB_SMP] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DB_SMP] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [DB_SMP] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'DB_SMP', N'ON'
GO
ALTER DATABASE [DB_SMP] SET QUERY_STORE = OFF
GO
USE [DB_SMP]
GO
/****** Object:  Table [dbo].[TB_CAT]    Script Date: 12/26/2022 10:56:45 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE TB_CAT(
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CAT_Name] [nvarchar](50) NULL,
	[CAT_Cover] [image] NULL,
 CONSTRAINT [PK_TB_CAT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_CuS]    Script Date: 12/26/2022 10:56:45 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE TB_CuS(
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Cus_name] [nvarchar](50) NULL,
	[Cus_phone] [nvarchar](50) NULL,
	[Cus_location] [nvarchar](50) NULL,
	[Cus_image] [image] NULL,
 CONSTRAINT [PK_TB_CuS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_Pur]    Script Date: 12/26/2022 10:56:45 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE TB_Pur(
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Supp_id] [int] NULL,
	[Pur_Name] [nvarchar](50) NULL,
	[Pur_Type] [nvarchar](50) NULL,
	[Pur_Cat] [nvarchar](50) NULL,
	[Pur_Sup] [nvarchar](50) NULL,
	[Pur_Det] [nvarchar](50) NULL,
	[Pur_Buy] [float] NULL,
	[Pur_Sell] [float] NULL,
	[Pur_Qt] [float] NULL,
	[Pur_Tsell] [float] NULL,
	[Pur_Tbuy] [float] NULL,
	[Pur_TRev] [float] NULL,
	[Cat_id] [int] NULL,
 CONSTRAINT [PK_TB_Pur] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_Sell]    Script Date: 12/26/2022 10:56:45 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE TB_Sell(
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Sell_Name] [nvarchar](50) NULL,
	[Sell_Cus] [nvarchar](50) NULL,
	[Sell_price] [float] NULL,
	[Sell_Qt] [float] NULL,
	[Sell_TPrice] [float] NULL,
	[Sell_Date] [datetime] NULL,
 CONSTRAINT [PK_TB_Sell] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_Supp]    Script Date: 12/26/2022 10:56:45 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE TB_Supp(
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Supp_Name] [nvarchar](50) NULL,
	[Supp_Phone] [nvarchar](50) NULL,
	[Supp_Email] [nvarchar](50) NULL,
	[Supp_Image] [image] NULL,
 CONSTRAINT [PK_TB_Supp] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_Users]    Script Date: 12/26/2022 10:56:45 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE TB_Users(
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[User_Name] [nvarchar](50) NULL,
	[User_Pass] [nvarchar](50) NULL,
	[User_Roll] [nvarchar](50) NULL,
	[User_State] [nvarchar](50) NULL,
 CONSTRAINT [PK_TB_Users] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TB_Pur]  WITH CHECK ADD  CONSTRAINT [FK_TB_Pur_TB_CAT] FOREIGN KEY([Cat_id])
REFERENCES [dbo].[TB_CAT] ([ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TB_Pur] CHECK CONSTRAINT [FK_TB_Pur_TB_CAT]
GO
ALTER TABLE [dbo].[TB_Pur]  WITH CHECK ADD  CONSTRAINT [FK_TB_Pur_TB_Supp] FOREIGN KEY([Supp_id])
REFERENCES [dbo].[TB_Supp] ([ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TB_Pur] CHECK CONSTRAINT [FK_TB_Pur_TB_Supp]
GO
USE [master]
GO
ALTER DATABASE [DB_SMP] SET  READ_WRITE 
GO
