using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using Sales_management_software.EPL;
using DevExpress.Utils.Extensions;

namespace Sales_management_software.PL
{
    public partial class FRM_SELL: Form
    {
        DB_SMPEntities1 db = new DB_SMPEntities1();
        TB_Sell tb_sell=new TB_Sell();
        BL.Methods methods = new BL.Methods(); 
        int id;

        public FRM_SELL()
        {

            InitializeComponent();

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            Sales_management_software.DB_SMPEntities1 dbContext = new Sales_management_software.DB_SMPEntities1();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.TB_Sell.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                gridControl1.DataSource = dbContext.TB_Sell.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        //ADD
        private void btn_add_Click(object sender, EventArgs e)
        {
            FRM_SELL_ADD frm_add = new FRM_SELL_ADD();
            frm_add.id = 0;
            frm_add.btn_add.Text = "add";
            frm_add.Show();
            
        }
        // Update
        private void btn_update_Click(object sender, EventArgs e)
        {
            Update_data();


        }
        // delete
        private void btn_delete_Click(object sender, EventArgs e)
        {
            Toast toast = new Toast();
            Dialog dialog = new Dialog();
            try
            {
                id = Convert.ToInt32(gridView1.GetFocusedRowCellValue("ID"));
                var rs = MessageBox.Show("delete", "are you sure?", MessageBoxButtons.YesNo);

                if (rs == DialogResult.Yes)
                {
                   tb_sell = db.TB_Sell.Where(X => X.ID == id).FirstOrDefault();
                    db.Entry(tb_sell).State = EntityState.Deleted;
                    db.SaveChanges();
                    toast.txt_caption.Text = "selling has been deleted";
                    toast.Show();   
                    Update_data();
                }
            }
            catch {
                dialog.txt_caption.Text = "no sell ";
                dialog.Width = this.Width;
                dialog.Show();
            }
           
           



        }


        private void Update_data()
        {
            db = new DB_SMPEntities1();
            gridControl1.DataSource = db.TB_Sell.ToList();
        }
        // dont need to edit 
        //private void btn_edit_Click(object sender, EventArgs e)
        //{
        //    FRM_SELL_ADD frm_add = new FRM_SELL_ADD();
        //    id = Convert.ToInt32(gridView1.GetFocusedRowCellValue("ID"));
        //    tb_sell = db.TB_Sell.Where(x=>x.ID==id).FirstOrDefault();
        //    frm_add.edt_name.Text = tb_sell.Sell_Name;
        //    frm_add.edt_sell.Text = tb_sell.ToString(); 
        //    frm_add.edt_qt.Text=tb_sell.Sell_Qt.ToString();   
        //    frm_add.txt_sell.Text=tb_sell.Sell_TPrice.ToString(); 
        //    frm_add.txt_buy.Text= tb_sell.Sell_price.ToString();  
        //    frm_add.id = id;
        //    frm_add.btn_add.Text = "edit";
        //    frm_add.Show();
        //}

        // search
        private void btn_search_Click(object sender, EventArgs e)
        {
            var _search=edt_search.Text;
            gridControl1.DataSource=db.TB_Sell.Where(x=>x.Sell_Name.Contains(_search)|| x.Sell_Cus.Contains(_search)||x.Sell_Date.ToString().Contains(_search)).ToList();
        }

        private void FRM_SUPP_Load(object sender, EventArgs e)
        {
            // TODO: This line of code loads data into the 'dB_SMPDataSet1.TB_Supp' table. You can move, or remove it, as needed.
            //this.tB_SuppTableAdapter.Fill(this.dB_SMPDataSet1.TB_Supp);

        }
    }
}
