using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using Sales_management_software.EPL;
using DevExpress.Utils.Extensions;
using Sales_management_software.DB;

namespace Sales_management_software.PL
{
    public partial class FRM_Users: Form
    {
        DB_SMPEntities db = new DB_SMPEntities();
        TB_Users tb_users = new TB_Users();
        BL.Methods methods = new BL.Methods(); 
        int id;

        public FRM_Users()
        {

            InitializeComponent();


            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            Sales_management_software.DB.DB_SMPEntities dbContext = new Sales_management_software.DB.DB_SMPEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.TB_Users.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                gridControl1.DataSource = dbContext.TB_Users.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
            TB_Users tb_users1 = new TB_Users("karam", "karam123", "User", "False");
            TB_Users tb_users2 = new TB_Users("david", "david123", "Admin", "True");

            if (db.TB_Users.Where(X => (X.User_Name == tb_users1.User_Name && X.User_Pass == tb_users1.User_Pass)).FirstOrDefault() == null)
            {
                db.TB_Users.Add(tb_users1);
                db.SaveChanges();
            }
            if (db.TB_Users.Where(X => (X.User_Name == tb_users2.User_Name && X.User_Pass == tb_users2.User_Pass)).FirstOrDefault() == null)
            {
                db.TB_Users.Add(tb_users2);
                db.SaveChanges();
            }
        }

        //ADD
        private void btn_add_Click(object sender, EventArgs e)
        {
            FRM_USERS_ADD frm_add = new FRM_USERS_ADD();
            frm_add.id = 0;
            frm_add.btn_add.Text = "add";
            frm_add.Show();
            
        }
        // Update
        private void btn_update_Click(object sender, EventArgs e)
        {
            Update_data();


        }
        // delete
        private void btn_delete_Click(object sender, EventArgs e)
        {
            Toast toast = new Toast();
            Dialog dialog = new Dialog();
            try
            {
                id = Convert.ToInt32(gridView1.GetFocusedRowCellValue("ID"));
                var rs = MessageBox.Show("delete", "are you sure?", MessageBoxButtons.YesNo);

                if (rs == DialogResult.Yes)
                {
                   tb_users = db.TB_Users.Where(X => X.ID == id).FirstOrDefault();
                    db.Entry(tb_users).State = EntityState.Deleted;
                    db.SaveChanges();
                    toast.txt_caption.Text = "user has been deleted";
                    toast.Show();   
                    Update_data();
                }
            }
            catch {
                dialog.txt_caption.Text = "no user ";
                dialog.Width = this.Width;
                dialog.Show();
            }
           
           



        }


        private void Update_data()
        {
            db = new DB_SMPEntities();
            gridControl1.DataSource = db.TB_Users.ToList();
        }
        // edit
        private void btn_edit_Click(object sender, EventArgs e)
        {
            FRM_USERS_ADD frm_add = new FRM_USERS_ADD();
            id = Convert.ToInt32(gridView1.GetFocusedRowCellValue("ID"));
            tb_users = db.TB_Users.Where(x=>x.ID==id).FirstOrDefault();
            frm_add.edt_name.Text = tb_users.User_Name;
            frm_add.edt_pass.Text = tb_users.User_Pass;
            frm_add.edt_roll.Text=tb_users.User_Roll;
            frm_add.id=id;
            frm_add.btn_add.Text = "edit";
            frm_add.Show();
        }
        // search
        private void btn_search_Click(object sender, EventArgs e)
        {
            var _search=edt_search.Text;
            gridControl1.DataSource=db.TB_Users.Where(x=>x.User_Name.Contains(_search)|| x.User_Roll.Contains(_search)).ToList();
        }

        private void FRM_SUPP_Load(object sender, EventArgs e)
        {
            

        }
    }
}
