using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using Sales_management_software.EPL;
using DevExpress.Utils.Extensions;

namespace Sales_management_software.PL
{
    public partial class FRM_PUR: Form
    {
        DB_SMPEntities1 db = new DB_SMPEntities1();
        TB_Pur tb_pur=new TB_Pur();
        BL.Methods methods = new BL.Methods(); 
        int id;

        public FRM_PUR()
        {

            InitializeComponent();

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            Sales_management_software.DB_SMPEntities1 dbContext = new Sales_management_software.DB_SMPEntities1();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.TB_Pur.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                gridControl1.DataSource = dbContext.TB_Pur.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        //ADD
        private void btn_add_Click(object sender, EventArgs e)
        {
            FRM_PUR_ADD frm_add = new FRM_PUR_ADD();
            frm_add.id = 0;
            frm_add.btn_add.Text = "add";
            frm_add.Show();
            
        }
        // Update
        private void btn_update_Click(object sender, EventArgs e)
        {
            Update_data();


        }
        // delete
        private void btn_delete_Click(object sender, EventArgs e)
        {
            Toast toast = new Toast();
            Dialog dialog = new Dialog();
            try
            {
                id = Convert.ToInt32(gridView1.GetFocusedRowCellValue("ID"));
                var rs = MessageBox.Show("delete", "are you sure?", MessageBoxButtons.YesNo);

                if (rs == DialogResult.Yes)
                {
                   tb_pur = db.TB_Pur.Where(X => X.ID == id).FirstOrDefault();
                    db.Entry(tb_pur).State = EntityState.Deleted;
                    db.SaveChanges();
                    toast.txt_caption.Text = "Purchase has been deleted";
                    toast.Show();   
                    Update_data();
                }
            }
            catch {
                dialog.txt_caption.Text = "no Purchase ";
                dialog.Width = this.Width;
                dialog.Show();
            }
           
           



        }


        private void Update_data()
        {
            db = new DB_SMPEntities1();
            gridControl1.DataSource = db.TB_Pur.ToList();
        }
        // edit
        private void btn_edit_Click(object sender, EventArgs e)
        {
            FRM_PUR_ADD frm_add = new FRM_PUR_ADD();
            id = Convert.ToInt32(gridView1.GetFocusedRowCellValue("ID"));
            tb_pur = db.TB_Pur.Where(x=>x.ID==id).FirstOrDefault();
            frm_add.edt_name.Text = tb_pur.Pur_Name;
            frm_add.edt_type.Text = tb_pur.Pur_Type;    
            frm_add.edt_cat.Text = tb_pur.Pur_Cat;
            frm_add.edt_sup.Text = tb_pur.Pur_Sup;  
            frm_add.edt_det.Text=tb_pur.Pur_Det;
            frm_add.edt_buy.Text = tb_pur.Pur_Buy.ToString();
            frm_add.edt_sell.Text = tb_pur.Pur_Sell.ToString(); 
            frm_add.edt_qt.Text=tb_pur.Pur_Qt.ToString();   
            frm_add.edt_tsell.Text=tb_pur.Pur_Tsell.ToString(); 
            frm_add.edt_tbuy.Text= tb_pur.Pur_Tbuy.ToString();
            frm_add.edt_trev.Text=tb_pur.Pur_TRev.ToString();   
            frm_add.id = id;
            frm_add.btn_add.Text = "edit";
            frm_add.Show();
        }
        // search
        private void btn_search_Click(object sender, EventArgs e)
        {
            var _search=edt_search.Text;
            gridControl1.DataSource=db.TB_Pur.Where(x=>x.Pur_Name.Contains(_search)|| x.Pur_Type.Contains(_search)||x.Pur_Cat.Contains(_search)).ToList();
        }

        private void FRM_SUPP_Load(object sender, EventArgs e)
        {
            // TODO: This line of code loads data into the 'dB_SMPDataSet1.TB_Supp' table. You can move, or remove it, as needed.
            //this.tB_SuppTableAdapter.Fill(this.dB_SMPDataSet1.TB_Supp);

        }
    }
}
