//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sales_management_software
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CuS
    {
        public int ID { get; set; }
        public string Cus_name { get; set; }
        public string Cus_phone { get; set; }
        public string Cus_location { get; set; }
        public byte[] Cus_image { get; set; }
    }
}
