//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sales_management_software.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_SMPEntities : DbContext
    {
        public DB_SMPEntities()
            : base("name=DB_SMPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_CAT> TB_CAT { get; set; }
        public virtual DbSet<TB_CuS> TB_CuS { get; set; }
        public virtual DbSet<TB_Pur> TB_Pur { get; set; }
        public virtual DbSet<TB_Sell> TB_Sell { get; set; }
        public virtual DbSet<TB_Supp> TB_Supp { get; set; }
        public virtual DbSet<TB_Users> TB_Users { get; set; }
    }
}
