//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sales_management_software.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Users
    {
        public int ID { get; set; }
        public string User_Name { get; set; }
        public string User_Pass { get; set; }
        public string User_Roll { get; set; }
        public string User_State { get; set; }

        public TB_Users()
        {
        }

        public TB_Users(string user_Name, string user_Pass, string user_Roll, string user_State)
        {
            User_Name = user_Name;
            User_Pass = user_Pass;
            User_Roll = user_Roll;
            User_State = user_State;
        }
    }
}
